// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TM.Models;

#nullable disable

namespace TM.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250627000038_AddPassengerNote")]
    partial class AddPassengerNote
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TM.Models.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Account__3214EC07745155F3");

                    b.ToTable("Account", (string)null);
                });

            modelBuilder.Entity("TM.Models.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .IsUnicode(false)
                        .HasColumnType("varchar(3)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("ModifiedById")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Country__3214EC072B231A63");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex(new[] { "Name" }, "UQ__Country__737584F6AEA61A1C")
                        .IsUnique();

                    b.HasIndex(new[] { "Code" }, "UQ__Country__A25C5AA7583A9C18")
                        .IsUnique();

                    b.ToTable("Country", (string)null);
                });

            modelBuilder.Entity("TM.Models.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("ModifiedById")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Location__3214EC070DDE3659");

                    b.HasIndex("CountryId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.ToTable("Location", (string)null);
                });

            modelBuilder.Entity("TM.Models.Entities.Passenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ArrivalFlightInfo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("AssignedPrice")
                        .HasColumnType("decimal(38, 0)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<decimal?>("CustomerPaid")
                        .HasColumnType("decimal(38, 0)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime");

                    b.Property<string>("DepartureFlightInfo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("DiscountPrice")
                        .HasColumnType("decimal(38, 0)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("HhFee")
                        .HasColumnType("decimal(38, 0)");

                    b.Property<string>("IdentityNumber")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("ModifiedById")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly?>("PassportExpiryDate")
                        .HasColumnType("date");

                    b.Property<string>("PassportNum")
                        .HasMaxLength(9)
                        .IsUnicode(false)
                        .HasColumnType("varchar(9)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("Reserved");

                    b.Property<int?>("TourId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Passenge__3214EC072CBEAAAC");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("TourId");

                    b.ToTable("Passenger", (string)null);
                });

            modelBuilder.Entity("TM.Models.Entities.Tour", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArrivalFlightInfo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("AvailableSeats")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DepartureAssembleTime")
                        .HasColumnType("datetime");

                    b.Property<string>("DepartureFlightInfo")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DepartureLocation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("DiscountPrice")
                        .HasColumnType("decimal(38, 0)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("FullPayDeadline")
                        .HasColumnType("datetime");

                    b.Property<decimal>("HhFee")
                        .HasColumnType("decimal(38, 0)");

                    b.Property<int?>("HoldTime")
                        .HasColumnType("int");

                    b.Property<bool?>("IsAutoHoldTime")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsVisaRequired")
                        .HasColumnType("bit");

                    b.Property<int?>("LocationId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("ModifiedById")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Note")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RoomNote")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasDefaultValue("Available");

                    b.Property<decimal>("SuggestPrice")
                        .HasColumnType("decimal(38, 0)");

                    b.Property<int>("TotalSeats")
                        .HasColumnType("int");

                    b.Property<DateTime?>("VisaDeadline")
                        .HasColumnType("datetime");

                    b.HasKey("Id")
                        .HasName("PK__Tour__3214EC073708CED1");

                    b.HasIndex("CreatedById");

                    b.HasIndex("LocationId");

                    b.HasIndex("ModifiedById");

                    b.ToTable("Tour", (string)null);
                });

            modelBuilder.Entity("TM.Models.Entities.TourSurcharge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(38, 0)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeleteAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("ModifiedById")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TourId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__TourSurc__3214EC0738DFF85C");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ModifiedById");

                    b.HasIndex("TourId");

                    b.ToTable("TourSurcharge", (string)null);
                });

            modelBuilder.Entity("TM.Models.Entities.Country", b =>
                {
                    b.HasOne("TM.Models.Entities.Account", "CreatedBy")
                        .WithMany("CountriesCreated")
                        .HasForeignKey("CreatedById");

                    b.HasOne("TM.Models.Entities.Account", "ModifiedBy")
                        .WithMany("CountriesModified")
                        .HasForeignKey("ModifiedById")
                        .HasConstraintName("FK__Country__Modifie__4F12BBB9");

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("TM.Models.Entities.Location", b =>
                {
                    b.HasOne("TM.Models.Entities.Country", "Country")
                        .WithMany("Locations")
                        .HasForeignKey("CountryId")
                        .IsRequired()
                        .HasConstraintName("FK__Location__Countr__5006DFF2");

                    b.HasOne("TM.Models.Entities.Account", "CreatedBy")
                        .WithMany("LocationsCreated")
                        .HasForeignKey("CreatedById");

                    b.HasOne("TM.Models.Entities.Account", "ModifiedBy")
                        .WithMany("LocationsModified")
                        .HasForeignKey("ModifiedById")
                        .HasConstraintName("FK__Location__Modifi__50FB042B");

                    b.Navigation("Country");

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("TM.Models.Entities.Passenger", b =>
                {
                    b.HasOne("TM.Models.Entities.Account", "CreatedBy")
                        .WithMany("PassengersCreated")
                        .HasForeignKey("CreatedById");

                    b.HasOne("TM.Models.Entities.Account", "ModifiedBy")
                        .WithMany("PassengersModified")
                        .HasForeignKey("ModifiedById")
                        .HasConstraintName("FK__Passenger__Modif__4E1E9780");

                    b.HasOne("TM.Models.Entities.Tour", "Tour")
                        .WithMany("Passengers")
                        .HasForeignKey("TourId")
                        .HasConstraintName("FK__Passenger__TourI__4D2A7347");

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("TM.Models.Entities.Tour", b =>
                {
                    b.HasOne("TM.Models.Entities.Account", "CreatedBy")
                        .WithMany("ToursCreated")
                        .HasForeignKey("CreatedById");

                    b.HasOne("TM.Models.Entities.Location", "Location")
                        .WithMany("Tours")
                        .HasForeignKey("LocationId")
                        .HasConstraintName("FK__Tour__LocationId__4B422AD5");

                    b.HasOne("TM.Models.Entities.Account", "ModifiedBy")
                        .WithMany("ToursModified")
                        .HasForeignKey("ModifiedById")
                        .HasConstraintName("FK__Tour__ModifiedBy__4C364F0E");

                    b.Navigation("CreatedBy");

                    b.Navigation("Location");

                    b.Navigation("ModifiedBy");
                });

            modelBuilder.Entity("TM.Models.Entities.TourSurcharge", b =>
                {
                    b.HasOne("TM.Models.Entities.Account", "CreatedBy")
                        .WithMany("TourSurchargesCreated")
                        .HasForeignKey("CreatedById");

                    b.HasOne("TM.Models.Entities.Account", "ModifiedBy")
                        .WithMany("TourSurchargesModified")
                        .HasForeignKey("ModifiedById")
                        .HasConstraintName("FK__TourSurch__Modif__52E34C9D");

                    b.HasOne("TM.Models.Entities.Tour", "Tour")
                        .WithMany("TourSurcharges")
                        .HasForeignKey("TourId")
                        .HasConstraintName("FK__TourSurch__TourI__51EF2864");

                    b.Navigation("CreatedBy");

                    b.Navigation("ModifiedBy");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("TM.Models.Entities.Account", b =>
                {
                    b.Navigation("CountriesCreated");

                    b.Navigation("CountriesModified");

                    b.Navigation("LocationsCreated");

                    b.Navigation("LocationsModified");

                    b.Navigation("PassengersCreated");

                    b.Navigation("PassengersModified");

                    b.Navigation("TourSurchargesCreated");

                    b.Navigation("TourSurchargesModified");

                    b.Navigation("ToursCreated");

                    b.Navigation("ToursModified");
                });

            modelBuilder.Entity("TM.Models.Entities.Country", b =>
                {
                    b.Navigation("Locations");
                });

            modelBuilder.Entity("TM.Models.Entities.Location", b =>
                {
                    b.Navigation("Tours");
                });

            modelBuilder.Entity("TM.Models.Entities.Tour", b =>
                {
                    b.Navigation("Passengers");

                    b.Navigation("TourSurcharges");
                });
#pragma warning restore 612, 618
        }
    }
}
